version: "3.8"

services:
    db:
        image: "postgres:13.2-alpine"
        restart: always
        ports:
            - "5433:5432" #remember this exposes 5433 to the host machine but the containers still use 5432 therefore python uses db:5432
        volumes:
            - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            POSTGRES_PASSWORD: "123"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
      
    python:
        build: . #tried to use alpine or slim python but kept throwing errors
        depends_on:
            db:
                condition: service_healthy
    datascience-notebook:
      image: jupyter/datascience-notebook  #tried to use minimal notebook but kept throwing errors
      volumes:
        - ./output/:/home/jovyan/work
      ports:
        - 8888:8888
